### ISSUE TITLE
CI tests failing

### ISSUE THREAD

**Issue by arthurbuhl** [Coding-Coach/coding-coach-front-end#134]
# Issue

## Description

Tests are failing on travis CI
Link - https://travis-ci.org/Coding-Coach/coding-coach/builds/438155969
Script - `npm run test`

## Failed Files

-  src/components/contact/__ tests __/SocialMedia.test.js
   -  `expect(value).toMatchSnapshot()` - Received value does not match stored snapshot 1.
-  src/components/contact/__ tests __/Contact.test.js
   - Unable to find an element with the alt text: people search logo 
- src/containers/App/__ tests __/App.test.js

**Comment by emmawedekind** [comment]
I've restarted the build... hopefully it passes now.

**Comment by arthurbuhl** [comment]
The build was actually terminated this time at it was running for more than 10 mins and a normal CI build usually takes about 2-3 mins:

```bash
Webpack Bundle Analyzer is started at http://127.0.0.1:8888
Use Ctrl+C to close it

No output has been received in the last 10m0s, this potentially indicates a stalled build 
or something wrong with the build itself.
Check the details on how to adjust your build configuration on: 
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

I think `Webpack Bundle Analyzer` script should not be present in Travis CI build. That might be the issue for the stalled build.

**Comment by linux-nerd** [comment]
@arthurbuhl, @emmawedekind The test for Contact.test.js failed because the alt text of logo was changed to 'Person using a magnifying glass to see the details of another guy.      ' and the one used in the test file is 'people search logo'

**Comment by arthurbuhl** [comment]
Ok, also I found that translation is not used in Contact.test.js and text there is hard-coded in English there. Will that cause an issue failing the test in any scenario?

**Comment by arthurbuhl** [comment]
Also, it would be great if we add test script to `lint-staged` so that before any commit we always make sure tests are running fine, something like 

https://github.com/facebook/create-react-app/issues/2336

**Comment by emmawedekind** [comment]
I think the build is passing now... can someone verify this?

**Comment by arthurbuhl** [comment]
@emmawedekind yes, CI is passing now. @crysfel just needs to approve the PR #136 and then you should be able to merge it.
