### ISSUE TITLE
Using $font variable

### ISSUE THREAD

**Issue by arthurbuhl** [Coding-Coach/coding-coach-front-end#94]
https://github.com/Coding-Coach/coding-coach/blob/d199d0becf073a1e43d2ea876f841adbe2a74644/src/containers/App/assets/app.scss#L30

https://github.com/Coding-Coach/coding-coach/blob/93df6511f0490abc4327a165ca19445d0d116bfb/src/theme/base/_elements.scss#L8

I think we should use `$font-` variable from [`_variables.scss`](https://github.com/Coding-Coach/coding-coach/blob/development/src/theme/base/_variables.scss) here in order to be consistent throughout the app.

**Comment by tureey** [comment]
Since the standard now is to use the variables we have available on `_variables.scss` can we close this? @emmawedekind @arthurbuhl
